export const XP_RULES = {
  CLAIM_REWARD: 20,
  CREATE_TOKEN: 2,
  SHARE_REF_LINK: 1,
  REF_LINK_USED: 5,
  VOTE_PROJECT: 2,
  COMMENT: 1,
  TOP10: 20,
  BUY_TOKEN: 1, // <--- AJOUTE CETTE LIGNE
};
